FROM python:3.12

COPY requirements.txt .

RUN pip3 install -r requirements.txt

RUN python3 -m spacy download en_core_web_sm

COPY extract.py .

COPY transform.py .

COPY load.py .

COPY etl.py .

COPY institutes.csv .

CMD ["python3", "etl.py"]


